language: scala
script: 
  - sbt ++$TRAVIS_SCALA_VERSION compile test:compile
  - sbt ++$TRAVIS_SCALA_VERSION test
scala:
  - 2.10.3
jdk:
  - oraclejdk7
notifications:
  email:
    - dcaoyuan@wandoujia.com
    - chenxingrun@wandoujia.com
