language: scala
scala:
- 2.10.3
jdk:
- openjdk7
script:
- sbt ++$TRAVIS_SCALA_VERSION compile test:compile
- sbt ++$TRAVIS_SCALA_VERSION test
after_success:
- |
  test "${TRAVIS_PULL_REQUEST}" = 'false' && test "${TRAVIS_JDK_VERSION}" = 'openjdk7' && sbt 'set resolvers += "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"' 'set credentials += Credentials("Sonatype Nexus Repository Manager", "oss.sonatype.org", System.getenv("SONATYPE_USER"), System.getenv("SONATYPE_PASS"))' ++${TRAVIS_SCALA_VERSION} publish
branches:
  only:
  - master
env:
  global:
  - secure: GmNbo4pJ/evd996E26uwWvCQP0c59HcizK2YSFO1gxH7PhBj3DMtnn02Oio22RobkDqWE8llbuBAS6GilcfoVhG8xMmlKDmpGCyy1v38r/c6wjnq3pc7O52Q/IzauWOLK3FFsFnPaNUm6S6JS0ayGzgRLsGwrKB4Obaz15tU0Hc=
  - secure: CHNfAWexK7xYyY+4anWFKWj0PjM9SPSiA4Tjn6lb+tWEqDw+Cqkj5RtmMy7A3u1omKQc80Bmc2JKYdr8/bEAsH/EE9ofgLW6DWpGpuZ3Q9k0NxTzQ0ubQTVo3p9mRRp5XnV5i3SaKlAocjd3PpTbxKoxNu8/oVn41EB/JUePKmM=
notifications:
  email:
  - dcaoyuan@wandoujia.com
  - chenxingrun@wandoujia.com
